id: P950FCCB8
initial_creation_type: input
source_metadata:
  title: Sherab Özer Series
  language: en
  description: 'Texts by and about Trengpo Tertön Sherab Özer (''phreng po gter ston
    shes rab ''od zer, 1518–1584) alias Drodül Lingpa:'
  volume:
    586f1a67f94244e7bd2ca3d50c00bfcb:
      title: Dispeller of All Samaya Corruptions and Pollutions
      parent: Damdrip Nyepa Kunsel
    8101f8e16f544a8a8a7fc7b411bdef32:
      title: 'Moonlight of Pacifying Amṛta: A Daily Visualization and Recitation for
        the Dispeller of All Samaya Corruptions and Pollutions'
      parent: Sādhanas
created_at: '2022-03-01T01:36:54.057392'
last_modified_at: '2022-03-01T01:36:54.057398'
